name: Bug Report
description: File a general bug report.
title: ''
labels: ['bug']
assignees:
  - bsagarzazu
body:
  - type: checkboxes
    id: previous-issues
    attributes:
      label: Previous Issues
      options:
        - label: I have checked that there is no existing issue regarding this bug.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what happened in as much detail as possible. Include steps to reproduce the bug, if applicable.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, copy and paste any relevant log output.
      render: shell
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: upload
    id: files
    attributes:
      label: Upload files
      description: If applicable, add files to help explain your problem.
    validations:
      required: false
