name: Feature Request
description: Suggest an idea for this project.
title: '[Request]:'
labels: ['enhancement']
assignees:
  - bsagarzazu
body:
  - type: checkboxes
    id: previous-issues
    attributes:
      label: Previous Issues
      options:
        - label: I have checked that there is no existing issue regarding this enhancement.
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see implemented.
    validations:
      required: true
  - type: checkboxes
    id: want-to-contribute
    attributes:
      label: Contribution
      options:
        - label: I want to implement this feature myself.
  - type: upload
    id: images
    attributes:
      label: Upload images
      description: If applicable, add images to help explain your request.
